### PR TITLE
Get up-to-date with upstream

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
I really recommend getting up-to-date with the upstream repository.

It probably requires some work, as your repo is really out of date. But I think it is a better to keep a little bit in sync.

### CODE REVIEW

**Comment by jacobperron** [comment]
Related to https://github.com/ros2/ros2/issues/937

@MatthijsBurgh Thanks for opening this pull request! After some discussion with the ROS 2 team, we would prefer if we didn't have to maintain this fork altogether. Perhaps we can instead point the ROS 2 project directly to the upstream repository? There are a couple things I can think of to make this work:

1. Get relevant code changes from this fork upstreamed
2. Work with orocos maintainers to bloom-release a version into ROS Rolling (same process as making a ROS 1 release)
    - E.g. we could provide you access to the existing ROS 2 release repository (https://github.com/ros2-gbp/orocos_kinematics_dynamics-release), or you could use the same repository for ROS 1 (https://github.com/orocos/orocos-kdl-release).

An alternative option is for us to track the released version provided by the OS package manager (e.g. `apt`) and maintain a "vendor" package for Windows and macOS (or maybe we could use `brew`). This vendor package would use CMake to clone and build orocos_kinematics_dynamics as necessary on some platforms.

IMO, tracking the upstream fork directly seems like a cleaner solution. Thoughts?

**Comment by jacobperron** [comment]
FWIW, I can help look into upstreaming changes (if any) that are required for ROS 2.

**Comment by MatthijsBurgh** [comment]
@jacobperron I am open to get the required changes from ros2 to upstream.

I have no experience yet with releasing yet. That has always been done by @smits. But I am open to learn this and/or work on this together with the ros2 maintainers.

Could you start with opening PRs to the upstream with the required changes?

**Comment by MatthijsBurgh** [comment]
@jacobperron I haven't seen any PR yet. Anything holding you back or just didn't have time yet?

**Comment by jacobperron** [comment]
@MatthijsBurgh Just time; thanks for the bump. I'll spend a little time now and see if I get anywhere.

**Comment by jacobperron** [comment]
@MatthijsBurgh I've opened https://github.com/orocos/orocos_kinematics_dynamics/pull/366, though I think it's a good addition, I don't think it's strictly required for ROS 2 to link against orocos-kdl.

See https://github.com/ros2/ros2/pull/1208 for a discussion on tracking upstream orocos-kdl.

**Comment by MatthijsBurgh** [comment]
@jacobperron https://github.com/orocos/orocos_kinematics_dynamics/pull/366 has been merged. Do you require more PRs?

**Comment by MatthijsBurgh** [comment]
@jacobperron any more PRs needed?

**Comment by jacobperron** [comment]
@MatthijsBurgh Sorry, I've been busy with other things lately. After a discussion with the team, I've created a "vendor" package for orocos_kdl that ensures the package is available on all supported platforms. As part of the process, I'm trying to get the Python bindings to work, which is where I'm currently stuck: https://github.com/ros2/orocos_kdl_vendor/pull/1#discussion_r782659061

Basically, after building orocos_kdl from source I don't seem to be able to `import PyKDL` from a Python interpreter. Any ideas?

**Comment by MatthijsBurgh** [comment]
@jacobperron I assume python is not able to find the `pykdl*.so`. In that case you need to do some investigation of the `PYTHONPATH`. It should include the path of where the library is located.

In case it can find the library, but fails to import. I could have issue finding the cpp library. That is a bit more difficult. But also not my expertise.

**Comment by jacobperron** [comment]
Alright, I think I resolved the PYTHONPATH issue in the vendor package (thanks!).

Closing this PR in favor of https://github.com/ros2/ros2/pull/1208.

**Pull request closed without merging**
