### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by ivanpauno**
Merging upstream master in `ros2` branch, resolving conflicts.

Particurlarly, this PR is included https://github.com/orocos/orocos_kinematics_dynamics/pull/215, which should solve our problems in Focal build.

### CODE REVIEW

**Comment by ivanpauno** [comment]
@jacobperron FYI.

IDK if there is a better way of sync with upstream master than doing this.
AFAIS, we haven't diverged much, though we haven't updated with upstream recently.

**Comment by tfoote** [comment]
Related orocos_kdl is also upstream: https://github.com/ros/rosdistro/pull/23841 We might want to use that instead of this. Another simple solution would be to push our patches back upstream. They're still active in maintaining and would probably be willing to make releases into ROS 2 as well as ROS 1 if it's just doing the releases.

**Comment by jacobperron** [comment]
@ivanpauno I think switching to the upstream orocos_kdl package is the best option, making it one less thing that we should maintain.

**Comment by ivanpauno** [comment]
@tfoote @jacobperron Do you mean creating a `ros2` branch in the upstream repo?

AFAIS the only differences between our fork and upstream are:
- Updated CMakelists.txt
- Updated package.xml
- Different ways of finding eigen (we use https://github.com/ros2/eigen3_cmake_module)
- We use `unique_ptr` instead of `scoped_ptr` (no dependency on boost).
- Deleted metapackage.

> They're still active in maintaining and would probably be willing to make releases into ROS 2 as well as ROS 1 if it's just doing the releases.

I think that it would be a bit more than just releasing, as we would need two branches. Some of the differences can probably be maintained in the same branch with some conditional logic
Maintaining both branches synchronized should be easy though.

**Comment by jacobperron** [comment]
I was referring to the rosdistro PR; we can try using the version of orocos_kdl that ships with Ubuntu.

**Comment by ivanpauno** [comment]
> I was referring to the rosdistro PR; we can try using the version of orocos_kdl that ships with Ubuntu.

That's ok by me. I will add an item in next week agenda to discuss the alternatives.

**Comment by ivanpauno** [comment]
> I was referring to the rosdistro PR; we can try using the version of orocos_kdl that ships with Ubuntu.

What about windows?

**Review by jacobperron — APPROVED** [review]
Approval pending green CI testing the dependent packages: `robot_state_publisher`, `tf2_kdl`, `kdl_parser` and `kdl_parser_py`.

**Comment by ivanpauno** [comment]
> Approval pending green CI testing the dependent packages: robot_state_publisher, tf2_kdl, kdl_parser and kdl_parser_py.

`kdl_parser_py` is being ignored (with an `AMENT_IGNORE` file), so I'm not including it.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/9526/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5236/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/7782/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/9452/)

**Comment by ivanpauno** [comment]
* Focal [Build Status](http://ci.ros2.org/job/ci_linux/9528/)

**Pull request merged**
